### PR TITLE
fixed issue #88:Now button dimension is succefully changing after selecting from KNOBS tab

### LINKED ISSUE #88: [BUG] Dimension props is not working  in interactive examples of Button component
**Describe the bug**
In interactive examples of Button component, dimension of button is not changing as required after selecting dimension from dimension drop down menu in KNOBS tab

**To Reproduce**
1. Go to interactive examples of Button component
2. Select on Dimensions drop down menu
3. See error

**Expected behavior**
Button size should be changed  as requirred after selecting dimension

**Other Required Information (please complete the following information):**
 - OS: ubuntu
 - Browser : chrome
 

**Additional context**
This error can be seen [here]( https://italia.github.io/design-react-kit/?knob-Variazioni=primary&knob-Dimensioni=sm&knob-Attivo=true&knob-Label=&selectedKind=Componenti%2FButton&selectedStory=Esempi%20interattivi&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

### PR DESCRIPTION
**Pull request by RMCoder198**
Fixes #88 

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
After change , dimension drop down is working succefully in Button component
fix88

### CODE REVIEW

**Comment by sanyamdogra** [comment]
@RMCoder198 Thanks for the PR, but the current working branch is `next` and not `master`. Please work on that.

**Comment by RMCoder198** [comment]
@sanyamdogra ok.

**Comment by RMCoder198** [comment]
@sanyamdogra ok. Thanks for letting me know.

**Comment by RMCoder198** [comment]
No need to push in master branch

**Pull request closed without merging**
