### PR TITLE
918 resolve deprecations warning 

### PR DESCRIPTION
**Pull request by sabato-galasso**
Fixes #

#### PR Checklist

- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (if applicable).
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [ ] I have added necessary documentation (if appropriate).

#### Changes proposed in this Pull Request:

- Resolved deprecations warning DocGen

### CODE REVIEW

**Review by dej611 — COMMENTED** [review]
Storybook version seems to not have been touched. Maybe you mean to update to latest `react-docgen-typescript-plugin` package?

**Comment by sabato-galasso** [comment]
> Storybook version seems to not have been touched. Maybe you mean to update to latest `react-docgen-typescript-plugin` package?

I renamed the issue name

**Review by dej611 — APPROVED** [review]
Not all deprecations have been solved, but there are less now.

**Comment by sabato-galasso** [comment]
> Not all deprecations have been solved, but there are less now.
fixed minor deprecation warning in @rollup/plugin-replace

**Pull request merged**
