### PR TITLE
Handle Babel config warning

### LINKED ISSUE #656: [BUG] Take care of Babel configuration warning
**Is your feature request related to a problem? Please describe.**
When compiling the toolkit the following warning gets logged in the console a million times:

```
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "false" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": false }]
to the "plugins" section of your Babel config.
```

Take care of it by following directions to fix it.

### PR DESCRIPTION
**Pull request by ankingcodes**
Fixes #656 

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

Fixes the issue by using instructions given in issue, i.e., adding `["@babel/plugin-proposal-private-methods", { "loose": false }]` to babel plugins.

### CODE REVIEW

**Comment by ankingcodes** [comment]
@dej611 - Ready for review 🚀! Not sure why the circleci build failed. Do let me know for changes.

**Comment by dej611** [comment]
The new version of Gatsby requires a newer version on Node.js for the job and it fails.
When #686 gets merged in `master`, could you please merge the latest `master` in here?

**Comment by dej611** [comment]
Please merge latest `master` in here to make all jobs run.

**Comment by ankingcodes** [comment]
@dej611 - Ready for merge 👍🏻

**Review by dej611 — APPROVED** [review]

**Pull request merged**
