### PR TITLE
Add BackButton component and initial documentation around it

### LINKED ISSUE #713: [FEATURE] Implement buttons "Torna su" e "Torna indietro"
**Describe the solution you'd like**

Create a "Torna su" e "Torna indietro" components based on the original Bootstrap Italia components:
* https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/torna-indietro/
* https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/torna-su/

For each component:

* [ ] Create the basic component
* [ ] Cover all the variants
* [ ] Create a Storybook set of stories based on the BI documentation

Notes:

* use BI classes to style the component.
* minimize the amount of extra CSS to style in this component

### PR DESCRIPTION
**Pull request by foysalit**
Fixes #713

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (if applicable).
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [x] I have added necessary documentation (if appropriate).

#### Short description of what this resolves:
This PR adds a new component for back button which internally uses the `Button` and the `Icon` component.

#### Changes proposed in this Pull Request:
- The general Readme.md still had reference that said all components live inside `src/components` which is not true at the moment so this PR updates the doc accordingly.
- Like me, many other devs may be using intellisense based IDEs which drops an `.idea` folder in the root of the project. Adding that folder to `.gitignore` will help keep the project clean from such content.

### CODE REVIEW

**Comment by foysalit** [comment]
When I run `yarn test` locally, all tests seem to pass without issues. There are some warning messages but they seem unrelated. Can you help me find out why the tests are failing on CI?

Screenshot 2021-10-12 at 16 35 26

**Comment by dej611** [comment]
Hi @foysalit any update?

**Comment by foysalit** [comment]
Hey @dej611 sorry but I think it's time that I accepted that I will not actually make time to come back to this any time soon even though I would very much like to :(
Please accept my apologies and hopefully you'll find someone else to wrap this up for you.

**Comment by dej611** [comment]
Do not worry. Thanks for your contribution so far.
When you want to get back, just pick a task from the issues list

**Pull request closed without merging**
