### PR TITLE
fixes #88:Now button dimension is successfully changing after selecting from KNOBS tab

### LINKED ISSUE #88: [BUG] Dimension props is not working  in interactive examples of Button component
**Describe the bug**
In interactive examples of Button component, dimension of button is not changing as required after selecting dimension from dimension drop down menu in KNOBS tab

**To Reproduce**
1. Go to interactive examples of Button component
2. Select on Dimensions drop down menu
3. See error

**Expected behavior**
Button size should be changed  as requirred after selecting dimension

**Other Required Information (please complete the following information):**
 - OS: ubuntu
 - Browser : chrome
 

**Additional context**
This error can be seen [here]( https://italia.github.io/design-react-kit/?knob-Variazioni=primary&knob-Dimensioni=sm&knob-Attivo=true&knob-Label=&selectedKind=Componenti%2FButton&selectedStory=Esempi%20interattivi&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

### PR DESCRIPTION
**Pull request by RMCoder198**
Fixes #88 

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `next` branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
After change , dimension drop down is working successfully in Button component
xs

### CODE REVIEW

**Comment by RMCoder198** [comment]
@francescozaia Please merge this PR.

**Comment by RMCoder198** [comment]
@francescozaia  I don't know why but changes of this pull request are still not reflected in code in branch `next`.

**Comment by francescozaia** [comment]
I will check that out in a bit, thanks for letting me know!

**Comment by francescozaia** [comment]
@RMCoder198 [Re-added](https://github.com/italia/design-react-kit/commit/c041cf74f5a47b7a0de071840e68866bfe06f028) 🤷‍♂️

**Pull request merged**
