### PR TITLE
Hour input styles

### LINKED ISSUE #646: [FEATURE] Make hour Input version match the BI doc version
**Describe the solution you'd like**

It currently uses the native `time` input UI in the browser, but it wuld be better to match the BI version.

Extend the `Input` component (time version) based on the original Bootstrap Italia documentation:
https://italia.github.io/bootstrap-italia/docs/form/input-ora/

* [ ] Extend the `Input` component to handle time as in BI
* [ ] Add stories/examples for it

Notes:

* use BI classes to style the component.
* minimize the amount of extra CSS to style in this component ( possibly creating a set of reusable `react-select` styles objects reusable
* Probably build the component logic or add an external dependency to match it

### PR DESCRIPTION
**Pull request by NicolaFerracin**
Fixes #646 

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (if applicable).
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [x] I have added necessary documentation (if appropriate).

#### Short description of what this resolves:

Create a new `Input` component for displaying the selection of time (hh:mm).

For achieving the above I had to also add the icon and button features to the `Input` field.

#### Changes proposed in this Pull Request:

- add button prop to `Input`
- add icon prop to `Input`
- rewrite existing `Input` examples using html markup to use the new icon/button props
- create `TimeInput` component with logic
- Tests

There are a few points I'm not too sure about but I opted for at least completing the first draft of this:
- I think the bootstrap styles are missing some definitions. At least (1)the spacing at the bottom of the field and the fact that (2)the spinner control has a low z-index and goes below whatever content comes next
- I had to add some custom code to `InputContainer` for showing the error label. The design for the error for this input seems to be different from the other input fields. Is it an issue to report or an expected behaviour?
- There doesn't appear to be a 'clickOutside' component to handle closing the controls section when clicking outside. I tried using onBlur but it was behaving weirdly. Can I leave it as it is? It closes when selecting the main input or when clicking the button again

### CODE REVIEW

**Comment by NicolaFerracin** [comment]
ups, I think I opened this in the wrong place, I messed up the upstream. Please let me know if I need to move it, sorry!

**Review by dej611 — COMMENTED** [review]
:tada: Thanks for your contribution!

The functionality looks already pretty good! 🚀 

I had a quick code review and, while the feature works, I may recommend few changes.

Most of the changes in this PR are about tweaking the `Input` component (which is already a complex component) to let do few more things for the `TimeInput` wrapper. My idea would be to reduce the impact on the `Input` component, minimize its scope and outsourcing most of the new feature via the `TimeInput`.
Probably the first step in this direction would be to let the `Input` component return just an `input` component with a flag prop, which for consistence with the rest of the kit, I propose:

```ts
noWrapper?: boolean;
```

This flag will let an early return in the `Input` component as follow:
```js
if (noWrapper) {
      return (
        <Tag
          {...rest}
          {...extraAttributes}
          className={inputClasses}
          {...sharedAttributes}
        />
      );
    }
```

Once completed this the `InputContainer` can be restored in its previous state, and `TimeInput` could use an ad-hoc `TimeInputContainer` with the specific logic.

Right now the `TimeInputProps` are quite limited, making them extends the `InputProps` with some exclusion it will automatically inherit most of useful props also to compute things later on:

```ts
type UnusedProps = 'plaintext' | 'onBlur' | 'value' | 'type';

export interface TimeInputProps extends Omit<InputProps, UnusedProps> { ... }
```

Most of the classes passed over to the `*InputContainer` component comes from functions from the `utils.ts` which can be reused, starting from most of the `Input` props. The only missing bit I can think of is the `focus` state, which can be easily fetched from  the `Input` component:

```jsx
<TimeInputContainer
                wrapperClass={wrapperClass}
                activeClass={activeClass}
                infoTextClass={infoTextClass}
				...
              >
			<Input
                  {...attributes}
                  type='time'
                  label={label}
                  id={id}
                  placeholder={placeholder}
                  value={time}
                  onFocus={() => {
                    setIsOpen(false);
                    toggleFocus(true);
                  }}
                  onChange={(e) => onTimeChange(e.target.value)}
                  invalid={invalid}
                  onBlur={() => {
                    toggleFocus(false);
                    onBlur(time);
                  }}
                  noWrapper
                />
</TimeInputContainer>
```

At this point I think the `Input` story with button and icon you've changed in this story could be restored to its previous state. I see that is not correct, but with the new `noWrapper` utility it should be straightforward to build it properly with the [`reactstrap` `InputGroup*` components](https://reactstrap.github.io/components/input-group/) - this will be addressed in a separate PR, don't worry about it.

Probably this explanation is a bit long, so I've made a draft PR with most of the changes proposed here (mind I haven't tested it yeet, so probably there are some rough edges to address): https://github.com/italia/design-react-kit/compare/hour-input-styles...hour-input-styles-2

**Comment by dej611** [comment]
@NicolaFerracin still interested in fix this PR?

**Comment by NicolaFerracin** [comment]
@dej611 yes, absolutely! I had a few very busy days but I plan to check it within this week.

**Comment by NicolaFerracin** [comment]
I finally got around to work on it, sorry for the delay. I found it easier to just open a new MR, is that ok?

https://github.com/italia/design-react-kit/pull/779
It's basically what you had in your branch plus a couple of adjustments @dej611

**Pull request closed without merging**
