### PR TITLE
Fixed the alert component

### PR DESCRIPTION
**Pull request by sanyamdogra**
#### PR Checklist
- [x] My branch is up-to-date with the Upstream `next` branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixed the alert component.
##### Before
image

##### After 
image

#### Changes proposed in this pull request:
- Added description on the top of every alert component.
- PropTable is working fine.

### CODE REVIEW

**Comment by RMCoder198** [comment]
@sanyamdogra  You don't have to change code that much. just add `.addDecorator(withInfo)` .

Docs for addon-info:https://github.com/storybooks/storybook/blob/master/addons/info/README.md
Latest docs  recommends new way of implementing info addon although old way still works.
Other stories also follows old way so i am creating an issue to change them.

**Comment by sanyamdogra** [comment]
@RMCoder198, Thanks for your suggestion. I had used the new implementation in the previous PR but there was some issue with `withDocs ( )` that seems to work now. Our first goal should be to make all components work, then we can use better approaches. You may open an issue if you like.

**Comment by RMCoder198** [comment]
@sanyamdogra That new approach worked for me. what was issue with withDocs()?

**Comment by RMCoder198** [comment]
@sanyamdogra  dont change path of docs keep it like thi `./docs/Esempi.md`

**Comment by sanyamdogra** [comment]
@RMCoder198 It was certainly due to npm package failure, it works fine in yarn for me too.

**Comment by RMCoder198** [comment]
@sanyamdogra   we are using yarn in branch `next`. So i guess we should follow recommended way.

**Comment by sanyamdogra** [comment]
@RMCoder198 Yes (y)

**Comment by sanyamdogra** [comment]
Hey @francescozaia, you may review it, Thanks.

**Pull request merged**
