### PR TITLE
onClick attach to dropdown options

### LINKED ISSUE #121: Dropdown visible after option is selected in Select Component
**Describe the bug**
`Select` Component **dropdown** do not get closed after an option is selected from the dropdown.

**To Reproduce**
1. Go to _Select_ tab
2. Click on _input_ field
3. Click on any _option_ inside dropdown
4. The dropdown does not get closed.

**Expected behavior**
The **dropdown** with all the options should be not visible once an option is selected

**Screenshots**
Screenshot from 2019-03-18 16-07-56

**Other Required Information:**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 71

### PR DESCRIPTION
**Pull request by Diuda**
Fixes #121 

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `next` branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
`Select` component **dropdown** closes when options are being clicked.

### CODE REVIEW

**Comment by RMCoder198** [comment]
@Diuda  There are disadvantage of this feature in select multiple. So either this feature needs more working or there is no need of this feature. you can check it on preview
I have already created issue for 'select' component. You should create an issue for before PR so does our work does not collide. Now if you want to work together on this component i have no problem but please create an issue before PR to avoid collision of our work.

**Comment by Diuda** [comment]
@RMCoder198 I don't think there's a disadvantage as such with `multiple` component. We can click on _input_ again to select the next option for our Component. But I understand your point of bad UX to click on the input field again to select another option.

The dropdown not getting closed is not the given feature for any option Component in general so we need that to close for sure. 
What I propose we can do in this fix is passing the prop for multiple component and stopping the propagation of event when multiple component is selected

Also, I have already opened the issue of dropdown not getting closed long back. Please refer to issue #121 
I hope this resolves the confusion pertaining to this particular issue.

**Comment by RMCoder198** [comment]
Yes, you should improve it for multiple and group components.

**Comment by Diuda** [comment]
@RMCoder198 fixed it

**Comment by Diuda** [comment]
> Yes, you should improve it for multiple and group components.

This is fixed.

**Pull request merged**
